#!/usr/bin/env python3

#
# This file is part of CamLinX.
#
# Copyright (c) 2026 Florent Kermarrec <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

"""Generate a C header with FPGA CSR addresses from the LiteX csr.csv."""

import sys
import csv

def csr2h(csv_filename, h_filename):
    lines = [
        "/* Generated by csr2h.py from the LiteX csr.csv, do not edit. */",
        "",
        "#ifndef FPGA_CSR_H",
        "#define FPGA_CSR_H",
        "",
    ]
    with open(csv_filename, encoding="utf-8") as f:
        for row in csv.reader(r for r in f if not r.startswith("#")):
            group, name, addr, length, mode = row
            if group == "csr_register":
                lines.append(f"#define CSR_{name.upper():40s} {addr}")
            if group == "constant" and name.startswith("config_"):
                lines.append(f"#define CSR_CONST_{name.upper():34s} {addr}")
    lines += ["", "#endif /* FPGA_CSR_H */", ""]
    with open(h_filename, "w") as f:
        f.write("\n".join(lines))

if __name__ == "__main__":
    csr2h(sys.argv[1], sys.argv[2])
