#!/usr/bin/env python3

#
# This file is part of CamLink 4K.
#
# Copyright (c) 2026 Florent Kermarrec <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

"""Generate generated/edid.h from software/edid.py."""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "software"))
from edid import generate_edid

edid = generate_edid()
ext  = edid[128:]
phys = ext.index(bytes([0x03, 0x0c, 0x00])) + 3
with open(sys.argv[1], "w") as f:
    f.write("/* Generated by gen_edid.py, do not edit. */\n\n")
    f.write("#ifndef EDID_H\n#define EDID_H\n\n#include <stdint.h>\n\n")
    f.write(f"#define EDID_PHYS_OFFSET {phys}\n\n")
    f.write("static const uint8_t edid_data[256] = {\n")
    for i in range(0, 256, 16):
        f.write("    " + " ".join(f"0x{b:02x}," for b in edid[i:i+16]) + "\n")
    f.write("};\n\n#endif /* EDID_H */\n")
