#!/usr/bin/env python3

#
# This file is part of LiteCamLink.
#
# Copyright (c) 2026 Florent Kermarrec <florent@enjoy-digital.fr>
# SPDX-License-Identifier: BSD-2-Clause

"""Generate generated/sdram_init.h (PHY settings + DDR3 init sequence) from the gateware build's
sdram_phy.h (empty header for builds without DRAM)."""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "software"))
from sdram_phy import PhySettings

KINDS = {"delay": 0, "control": 1, "address": 2, "baddress": 3, "command": 4}

def main(phy_h, out):
    lines = [
        "/* Generated by gen_sdram.py, do not edit. */",
        "",
        "#ifndef SDRAM_INIT_H",
        "#define SDRAM_INIT_H",
        "",
    ]
    if os.path.exists(phy_h):
        p = PhySettings(phy_h)
        for name, value in [
            ("PHASES",       p.phases),
            ("DATABITS",     p.databits),
            ("DFI_DATABITS", p.dfi_databits),
            ("RDPHASE",      p.rdphase),
            ("WRPHASE",      p.wrphase),
            ("MODULES",      p.modules),
            ("DELAYS",       p.delays),
            ("BITSLIPS",     p.bitslips)]:
            lines.append(f"#define SDRAM_{name:13s} {value}")
        lines.append(f"#define SDRAM_{'MEMORY':13s} 0x{p.memory:x}")
        lines += [
            "",
            "#define SDRAM_STEP_DELAY    0 /* value: us. */",
            "#define SDRAM_STEP_CONTROL  1 /* value: DFII control. */",
            "#define SDRAM_STEP_ADDRESS  2 /* phase, value: address. */",
            "#define SDRAM_STEP_BADDRESS 3 /* phase, value: bank. */",
            "#define SDRAM_STEP_COMMAND  4 /* phase, value: command (issued). */",
            "",
            "struct sdram_step {",
            "    unsigned char kind, phase;",
            "    unsigned int  value;",
            "};",
            "",
            "static const struct sdram_step sdram_init_steps[] = {",
        ]
        for step in p.init_sequence():
            kind = step[0]
            if kind in ("delay", "control"):
                phase, value = 0, step[1]
            else:
                phase, value = step[1], step[2]
            lines.append(f"    {{{KINDS[kind]}, {phase}, 0x{value:x}}},")
        lines.append("};")
    lines += ["", "#endif /* SDRAM_INIT_H */", ""]
    with open(out, "w") as f:
        f.write("\n".join(lines))

if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
