/*
 * This file is part of LiteCamLink.
 *
 * Copyright (c) 2026 Florent Kermarrec <florent@enjoy-digital.fr>
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * ITE IT6802 HDMI receiver.
 *
 * The configuration values are derived from the register state observed on a stock Cam Link 4K
 * (stock firmware, no input) versus the post-reset state of the chip (see doc/HARDWARE.md). The
 * EDID is generated by software/edid.py (generated/edid.h).
 */

#include "fx3.h"
#include "i2c.h"
#include "it6802.h"

#include "generated/edid.h"

#define IT6802_ADDR    0x49 /* PCADR high. */
#define IT6802_EDID    0x50 /* EDID RAM address on the PC bus (programmed in reg 0x87). */

#define REG_BANK       0x0f
#define REG_SYS_STATUS 0x0a
#define REG_VID_MODE   0x99
#define REG_PCLK       0x9a

#define SYS_5V_DET     (1 << 0)
#define SYS_SCDT       (1 << 7)

static struct it6802_status status;

/* Register Access ------------------------------------------------------------------------------- */

static uint8_t current_bank = 0xff;

static int it6802_bank(uint8_t bank)
{
    int ret = 0;
    if (bank != current_bank) {
        ret = i2c_write(IT6802_ADDR, &(uint8_t){REG_BANK}, 1, &bank, 1);
        current_bank = ret ? 0xff : bank;
    }
    return ret;
}

int it6802_write(uint8_t bank, uint8_t reg, uint8_t value)
{
    if (it6802_bank(bank))
        return -1;
    return i2c_write(IT6802_ADDR, &reg, 1, &value, 1);
}

int it6802_read(uint8_t bank, uint8_t reg, uint8_t *value)
{
    if (it6802_bank(bank))
        return -1;
    return i2c_read(IT6802_ADDR, &reg, 1, value, 1);
}

/* Configuration --------------------------------------------------------------------------------- */

struct reg_value {
    uint8_t bank;
    uint8_t reg;
    uint8_t value;
};

/* Stock configuration (differences between post-reset and stock no-input states). */
static const struct reg_value config[] = {
    /* Auto resets. */
    {0, 0x11, 0xa0}, {0, 0x18, 0xa0},
    /* Input clock/receiver setup. */
    {0, 0x16, 0x88}, {0, 0x17, 0x80}, {0, 0x1d, 0x08}, {0, 0x1e, 0x00},
    {0, 0x2a, 0x32}, {0, 0x2b, 0x07}, {0, 0x2d, 0x23}, {0, 0x42, 0x12}, {0, 0x45, 0x23},
    {0, 0x31, 0x09}, {0, 0x49, 0x09}, {0, 0x35, 0x55}, {0, 0x4b, 0x55},
    /* Equalizer. */
    {0, 0x25, 0x1f}, {0, 0x3d, 0x1f},
    {1, 0xb5, 0x1f}, {1, 0xb8, 0x00}, {1, 0xbc, 0x06}, {1, 0xc0, 0x08}, {1, 0xcc, 0x00}, {1, 0xd2, 0x7f},
    /* Outputs: audio/video tri-stated until video is stable, drive strengths. */
    {0, 0x52, 0x3f}, {0, 0x53, 0x4f}, {0, 0x58, 0x33}, {0, 0x59, 0xaa},
    /* Audio clocks, packets, interrupts. */
    {0, 0x54, 0x11}, {0, 0x60, 0xbf}, {0, 0x63, 0x3f}, {0, 0x67, 0x00}, {0, 0x6a, 0x81},
    {0, 0x71, 0x00}, {0, 0x74, 0xa0}, {0, 0x77, 0x08}, {0, 0x7e, 0x40}, {0, 0x85, 0x0e},
    /* Output format: RGB, 8-bit, no CSC (updated when video is detected). */
    {0, 0x65, 0x00},
};

static int it6802_load_edid(void)
{
    uint8_t c0;
    int ret = 0;

    /* EDID RAM on the PC bus, DDC access disabled while writing. */
    ret |= it6802_write(0, 0x87, (IT6802_EDID << 1) | 1);
    ret |= it6802_read(0, 0xc0, &c0);
    ret |= it6802_write(0, 0xc0, c0 & ~0x03);
    for (int off = 0; off < 256 && !ret; off += 8) {
        uint8_t o = off;
        ret |= i2c_write(IT6802_EDID, &o, 1, &edid_data[off], 8);
        delay_us(2000);
    }

    /* Per-port physical address / checksums (the chip substitutes them on DDC reads). */
    ret |= it6802_write(0, 0xc1, EDID_PHYS_OFFSET);
    ret |= it6802_write(0, 0xc2, 0x10);
    ret |= it6802_write(0, 0xc3, 0x00);
    ret |= it6802_write(0, 0xc4, edid_data[127]);
    ret |= it6802_write(0, 0xc5, edid_data[255]);
    ret |= it6802_write(0, 0xc6, 0x20);
    ret |= it6802_write(0, 0xc7, 0x00);
    ret |= it6802_write(0, 0xc8, edid_data[127]);
    ret |= it6802_write(0, 0xc9, (uint8_t)(edid_data[255] + 0x10 - 0x20));

    /* Enable DDC access to the EDID RAM (0xC0 = 0x07, as observed on the stock firmware with a
     * working source) and remove the EDID RAM from the PC bus (as the stock firmware does). */
    ret |= it6802_write(0, 0xc0, 0x07);
    ret |= it6802_write(0, 0x87, 0x00);
    return ret;
}

static void it6802_hpd(int high)
{
    /* Bank 1, reg 0xB0[1:0]: 11 = HPD high, 01 = HPD low. */
    it6802_write(1, 0xb0, high ? 0x03 : 0x01);
    status.hpd = high;
}

int it6802_init(void)
{
    uint8_t id[4];
    int ret;

    current_bank = 0xff;
    ret = i2c_read(IT6802_ADDR, &(uint8_t){0x00}, 1, id, 4);
    status.present = !ret && id[0] == 0x54 && id[1] == 0x49 && id[2] == 0x02 && id[3] == 0x68;
    if (!status.present)
        return -1;

    it6802_hpd(0);
    for (unsigned i = 0; i < sizeof(config)/sizeof(config[0]); i++)
        ret |= it6802_write(config[i].bank, config[i].reg, config[i].value);
    ret |= it6802_load_edid();
    return ret;
}

/* Monitoring ------------------------------------------------------------------------------------ */

static uint16_t it6802_read16(uint8_t lo, uint8_t hi, uint8_t hi_mask, uint8_t hi_shift)
{
    uint8_t l = 0, h = 0;
    it6802_read(0, lo, &l);
    it6802_read(0, hi, &h);
    return (uint16_t)(((h >> hi_shift) & hi_mask) << 8) | l;
}

void it6802_service(void)
{
    static uint32_t last;
    uint8_t sys = 0;

    /* Poll every ~50ms. */
    static uint32_t retries;

    if (++last < 50000)
        return;
    last = 0;
    if (!status.present) {
        /* Chip held in reset until the FPGA is loaded: retry init (~1s period). */
        if (++retries >= 40) {
            retries = 0;
            it6802_init();
        }
        return;
    }

    if (it6802_read(0, REG_SYS_STATUS, &sys))
        return;
    status.sys_status = sys;

    /* HPD follows the source 5V. */
    if ((sys & SYS_5V_DET) && !status.hpd)
        it6802_hpd(1);
    if (!(sys & SYS_5V_DET) && status.hpd)
        it6802_hpd(0);

    if ((sys & SYS_SCDT) && !status.stable) {
        /* Video became stable: YUV 4:2:2 8-bit output (16-bit bus), outputs on. The input color
         * space comes from the AVI InfoFrame (bank 2 0x15 = PB1, Y[6:5]: 0 = RGB, 1 = YCbCr 4:2:2,
         * 2 = YCbCr 4:4:4): RGB -> YUV CSC for RGB sources, bypass for YCbCr sources. */
        uint8_t avi_pb1 = 0;
        it6802_read(2, 0x15, &avi_pb1);
        status.colorspace = (avi_pb1 >> 5) & 0x3;
        it6802_write(0, 0x65, status.colorspace ? 0x10 : 0x12);
        it6802_write(0, 0x50, 0xb0); /* Output clock inverted, no delay (middle of the sampling window). */
        it6802_write(0, 0x53, 0x40);
    }
    if (!(sys & SYS_SCDT) && status.stable)
        it6802_write(0, 0x53, 0x4f); /* Outputs tri-stated. */
    status.stable = !!(sys & SYS_SCDT);
    if (status.stable) {
        status.htotal  = it6802_read16(0x9c, 0x9d, 0x3f, 0);
        status.hactive = it6802_read16(0x9e, 0x9f, 0x3f, 0);
        status.vtotal  = it6802_read16(0xa3, 0xa4, 0x0f, 0);
        status.vactive = it6802_read16(0xa5, 0xa4, 0x0f, 4);
        it6802_read(0, REG_PCLK,     &status.pclk_reg);
        it6802_read(0, REG_VID_MODE, &status.video_mode);
    }
}

const struct it6802_status *it6802_get_status(void)
{
    return &status;
}
